AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution with path-based behaviors and optional WAFv2 WebACL.

Parameters:
  OriginDomainName:
    Type: String
  AlternateDomainName:
    Type: String
    Default: ''
  AcmCertificateArn:
    Type: String
    Default: ''
  HostedZoneId:
    Type: String
    Default: ''
  PriceClass:
    Type: String
    Default: PriceClass_All
    AllowedValues: [PriceClass_All, PriceClass_200, PriceClass_100]
  OriginProtocolPolicy:
    Type: String
    Default: http-only
    AllowedValues: [http-only, https-only, match-viewer]
  ApiPathPattern:
    Type: String
    Default: /api/*
  StaticPathPattern:
    Type: String
    Default: /static/*
  WebACLArn:
    Type: String
    Default: ''
    Description: Optional WAFv2 WebACL ARN (CLOUDFRONT scope). Leave empty to skip.

Conditions:
  UseCustomDomain: !And
    - !Not [!Equals [!Ref AlternateDomainName, '']]
    - !Not [!Equals [!Ref AcmCertificateArn, '']]
  CreateR53: !And
    - !Condition UseCustomDomain
    - !Not [!Equals [!Ref HostedZoneId, '']]
  UseWAF: !Not [!Equals [!Ref WebACLArn, '']]

Resources:
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        IPV6Enabled: true
        Comment: Distribution with path-based behaviors and optional WAF
        PriceClass: !Ref PriceClass
        Origins:
          - Id: app-alb-origin
            DomainName: !Ref OriginDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: !Ref OriginProtocolPolicy
              OriginSSLProtocols: [TLSv1.2]
        DefaultCacheBehavior:
          TargetOriginId: app-alb-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        CacheBehaviors:
          - PathPattern: !Ref ApiPathPattern
            TargetOriginId: app-alb-origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
          - PathPattern: !Ref StaticPathPattern
            TargetOriginId: app-alb-origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Aliases: !If [UseCustomDomain, [!Ref AlternateDomainName], []]
        ViewerCertificate: !If
          - UseCustomDomain
          - AcmCertificateArn: !Ref AcmCertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        HttpVersion: http2and3
        DefaultRootObject: index.html
        WebACLId: !If [UseWAF, !Ref WebACLArn, !Ref "AWS::NoValue"]

  RecordA:
    Type: AWS::Route53::RecordSet
    Condition: CreateR53
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref AlternateDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
  RecordAAAA:
    Type: AWS::Route53::RecordSet
    Condition: CreateR53
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref AlternateDomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  DistributionId:
    Value: !Ref Distribution
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
