AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB Global Table for global low-latency reads and resilience

Parameters:
  TableName:
    Type: String
    Default: traffic-session
  PrimaryRegion:
    Type: String
    Default: ap-northeast-2
  SecondaryRegion:
    Type: String
    Default: ap-northeast-1
  TTLAttributeName:
    Type: String
    Default: ttl

Resources:
  GlobalTable:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: !Ref TTLAttributeName
        Enabled: true
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: userId-createdAt-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Replicas:
        - Region: !Ref PrimaryRegion
        - Region: !Ref SecondaryRegion

Outputs:
  TableName:
    Value: !Ref TableName
  TableArn:
    Value: !GetAtt GlobalTable.Arn
